repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.5.0
    hooks:
    - id: gitleaks

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
